# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773c71e3c5add388d7082b15317f646f2798815d234622b9ab1a66b52de33b9317882f64176a81b64cc2b2f738dc8d303f481af44ec6e0cf3de75eb6a69ad076

test:
  secret_key_base: 041c381b3032b7ef972c884a3e006d2381cc0c482e759552f29531f779a522f7ecc8599fd6583144643bffa92b8540c4fb2ba045751f417a045c143dad19b5a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
